# files path, change for each server
PATH: D:\javaProjects\minecraftPlugins\PrisonPlugin\src\tomer\prison\Files


# blocks and their worth
BLOCK_WORTH:
  COBBLESTONE: 1
  COAL: 3
  IRON_ORE: 7
  COAL_BLOCK: 12
  IRON_BLOCK: 20
  REDSTONE: 17
  GOLD_ORE: 22
  DIAMOND: 30
  GOLD_BLOCK: 37
  EMERALD: 40
  DIAMOND_BLOCK: 80
  EMERALD_BLOCK: 150

MENU:
  SIZE: 27


BALANCE:
  SIGN: $
  START: 0

RANK:
  DEFAULT: a

RANKUP:
  a: 0
  b: 1000
  c: 3000
  d: 10000