# blocks and their worth
BLOCK_WORTH:
  STONE: 1
  COAL_ORE: 3
  IRON_ORE: 7
  COAL_BLOCK: 12
  IRON_BLOCK: 20
  REDSTONE_ORE: 17
  GOLD_ORE: 22
  DIAMOND_ORE: 30
  GOLD_BLOCK: 37
  EMERALD_ORE: 40
  DIAMOND_BLOCK: 80
  EMERALD_BLOCK: 150

MENU:
  SIZE: 27